# Generated by Django 5.2.3 on 2025-06-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('live_url', models.URLField(blank=True, null=True)),
                ('code_url', models.URLField(blank=True, null=True)),
                ('tech_stack', models.CharField(max_length=200)),
            ],
        ),
    ]
